// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9lIk9bUj_ZWtgvszHLiu6ieA47MkPXtI',
    appId: '1:628400763481:web:cf8cfe08256345e0c83748',
    messagingSenderId: '628400763481',
    projectId: 'sport-events-d3ad6',
    authDomain: 'sport-events-d3ad6.firebaseapp.com',
    storageBucket: 'sport-events-d3ad6.appspot.com',
    measurementId: 'G-DW130F9JF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBMkIzo7_dNE4YTrjmx1SMGfPGNFSmVBc',
    appId: '1:628400763481:android:e8d311d9c385c75dc83748',
    messagingSenderId: '628400763481',
    projectId: 'sport-events-d3ad6',
    storageBucket: 'sport-events-d3ad6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANR0FtYo1mkCdpP_b1KRlSC83JZmerpeU',
    appId: '1:628400763481:ios:0f88fd1afd5b8f74c83748',
    messagingSenderId: '628400763481',
    projectId: 'sport-events-d3ad6',
    storageBucket: 'sport-events-d3ad6.appspot.com',
    iosBundleId: 'com.example.sportEvents',
  );
}
